### PR TITLE
Adding ACL auto approver fields

### PR DESCRIPTION
**Pull request by rayjanoka**
Hey, thanks for creating this. I added the new `autoApprovers` fields and tested it.

[https://tailscale.com/blog/auto-approvers/](https://tailscale.com/blog/auto-approvers/)

Let me know if anything is missing.

Thanks! Ray

### CODE REVIEW

**Comment by davidsbond** [comment]
Hello @rayjanoka, thanks for your pull request, much appreciated. I'll run the tests and give everything a look over.

**Review by davidsbond — APPROVED** [review]
This looks good to me, I double checked the documentation and this matches what Tailscale say!

Thanks again!

**Comment by rayjanoka** [comment]
bigup David, will this trigger a new build of the tf-provider? 😃

**Comment by davidsbond** [comment]
@rayjanoka, I've just told dependabot to check for updates on the provider:

https://github.com/davidsbond/terraform-provider-tailscale/pull/96

**Comment by davidsbond** [comment]
@rayjanoka give https://github.com/davidsbond/terraform-provider-tailscale/releases/tag/v0.9.5 some time to release and you should have access to those fields in the terraform provider. The terraform registry can take a little while to grab the new version.

If anything goes awry please feel free to raise another issue on that repo or this one.

**Pull request merged**
